apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledlemon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/ledlemon.git
    targetRevision: HEAD
    path: infra/charts/ledlemon
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pixel-game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
